import{A as h,S as v,K as L,N as w,i as y,a as f,b as C}from"./assets/vendor-qx7QalA8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))a(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(s){if(s.ep)return;s.ep=!0;const o=i(s);fetch(s.href,o)}})();const b=document.querySelector(".logo-text-js"),k=b.textContent.trim();b.innerHTML="";function x(e){return[...e].map(t=>`<span class="letter-js">${t}</span>`).join("")}b.insertAdjacentHTML("afterbegin",x(k));const M=document.querySelector(".header-nav-btn");M.addEventListener("click",B);function B(e){let t;e.target.tagName==="SPAN"?(t=document.querySelector(".nav-menu-list"),console.log(t),setTimeout(()=>{t.classList.toggle("menu-visible")},5e3)):(t=document.querySelector(".mobile-menu"),t.addEventListener("click",E)),t.classList.toggle("menu-visible")}function E(e){e.target.classList.contains("menu-visible")||(e.currentTarget.classList.toggle("menu-visible"),e.currentTarget.removeEventListener("click",E))}document.addEventListener("DOMContentLoaded",()=>{new h(".about-me-accordion-list",{duration:400,showMultiple:!0,elementClass:"js-acc-item",triggerClass:"js-toggle-btn",panelClass:"js-accordion-content-wrap",activeClass:"js-ac-content-open"}).open(0)});const q=["HTML/CSS","JavaScript","React","Node.js","React Native","Soft Skills","MySQL"],_=document.querySelector(".js-swiper-list");function F(e){return e.map((t,i)=>`<li class="swiper-slide">
            <p class="js-slide-text">
              ${t}
            </p>
     </li>`).join("")}_.insertAdjacentHTML("afterbegin",F(q));new v(".js-about-me-swiper-wrapper",{modules:[L,w],containerModifierClass:"js-",slideActiveClass:"js-slide-active",loop:!0,loopedSlides:12,slidesPerView:2,simulateTouch:!0,touchRatio:1,watchSlidesProgress:!0,navigation:{nextEl:".js-next-slide-btn"},keyboard:{enabled:!0,onlyInViewport:!0},breakpoints:{768:{slidesPerView:3},1440:{slidesPerView:6}}});const T=["#react","#js","#node js","#git"],P="Programming Across Borders: Ideas, Technologies, Innovations",O="https://zakhar-t.github.io/TeamProject_Portfolio_PG7/",R="See project",$=document.querySelectorAll(".projects-slide-content-js");function A(e,t,i,a){return`
    <ul class="slide-content-list-js">${e.map(o=>`<li class="slide-content-item-js">
          <p>${o}</p>
       </li>`).join("")}</ul>
    <p class="slide-content-text-js">${t}</p>
    <a class="slide-content-link-js" href="${i}" target="_blank" rel="noopener noreferrer">
      ${a}
    </a>`}$.forEach(e=>{e.insertAdjacentHTML("afterbegin",A(T,P,O,R))});const p=document.querySelector(".swiper-btn-right-js"),g=document.querySelector(".swiper-btn-left-js");new v(".projects-swiper-js",{direction:"horizontal",simulateTouch:!0,speed:1200,slidesPerView:1,spaceBetween:20,modules:[L,w],navigation:{nextEl:p,prevEl:g},keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!1},on:{reachEnd:()=>{p.disabled=!0},reachBeginning:()=>{g.disabled=!0},fromEdge:()=>{p.disabled=!1,g.disabled=!1}}});new h(".faq-accordion-list",{duration:400,showMultiple:!0});const N=document.querySelector(".covers"),I=new IntersectionObserver((e,t)=>{e.forEach(i=>{i.isIntersecting?i.target.classList.add("onScreen"):i.target.classList.remove("onScreen")})},{root:null,rootMargin:"100px",threshold:0});I.observe(N);async function V(){try{return(await f.get("https://portfolio-js.b.goit.study/api/reviews")).data}catch(e){console.log(e)}}async function H(){const e=await V(),t=document.querySelector(".reviews-list");if(e.length===0){const n=document.createElement("p");n.classList.add("review-error-massage"),n.textContent="Reviews is Not Found",t.appendChild(n);return}const i=document.createDocumentFragment();e.forEach(({author:n,avatar_url:d,review:c})=>{const r=document.createElement("li");r.classList.add("reviews-item"),r.classList.add("swiper-slide"),r.innerHTML=`
    <img src="${d}" alt="${n} review" class="reviews-img">
    <h3 class="reviews-name">${n}</h3>
    <p class="reviews-text-content">${c}</p>
  `,i.appendChild(r)}),t.appendChild(i);const a=document.querySelector(".reviews-button-next"),s=document.querySelector(".reviews-button-prev");new v(".reviews-swiper",{direction:"horizontal",simulateTouch:!0,spaceBetween:16,breakpoints:{1440:{slidesPerView:4,spaceBetween:16},768:{slidesPerView:2,spaceBetween:16},320:{slidesPerView:1,spaceBetween:16}},modules:[w],navigation:{nextEl:a,prevEl:s},on:{reachEnd:()=>{a.disabled=!0},reachBeginning:()=>{s.disabled=!0},fromEdge:()=>{a.disabled=!1,s.disabled=!1}}}),document.querySelectorAll(".reviews-item").forEach(n=>{n.addEventListener("click",d=>{n.getBoundingClientRect();const c=n.cloneNode(!0),r=document.createElement("div");r.classList.add("reviews-modal");const m=document.createElement("div");m.classList.add("container"),c.classList.add("card-clone"),c.style.margin="0";const u=document.createElement("button");u.classList.add("reviews-modal-close"),u.textContent="Close",c.appendChild(u),r.appendChild(m),m.appendChild(c),document.body.appendChild(r),u.addEventListener("click",()=>{r.remove()}),r.addEventListener("click",S=>{S.target===r&&r.remove()})})})}H();function j(){const e=document.querySelector(".review-error-massage");if(!e)return;const t=e.getBoundingClientRect();t.top<window.innerHeight&&t.bottom>0&&(y.error({title:"Oops!",message:"No reviews found for this section.",timeout:5e3,backgroundColor:"#2c2f33",titleColor:"#FF6B6B",messageColor:"#FFFFFF",icon:"fas fa-exclamation-circle",iconColor:"#FF6B6B",position:"topRight",progressBarColor:"#FF6B6B",transitionIn:"fadeInDown",transitionOut:"fadeOutUp"}),window.removeEventListener("scroll",j))}window.addEventListener("scroll",j);const l=document.body,D=document.querySelector(".work-together-form");f.defaults.baseURL="https://portfolio-js.b.goit.study/api";async function z(e,t){return await f.post("/requests/",{email:e,comment:t})}D.addEventListener("submit",U);function U(e){e.preventDefault();const t=e.target,{userEmail:i,userComments:a}=t.elements;z(i.value,a.value).then(s=>{const o=C.create(` 
        <div id="modalW" class="backdrop">
            <div class="modal-window">
                <button class="modal-btn" type="button" aria-label="close-button">
                     <svg class="modal-btn-icon" xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="none">
                        <path stroke="#FAFAFA" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 7 7 21M7 7l14 14"/>
                    </svg>
                </button>
            <div class="modal-wrapper">
                <h3 class="modal-title">${s.data.title}</h3>
                <p class="modal-text">${s.data.message}</p>
            </div>
            </div>
        </div>`);o.show();const n=document.getElementById("modalW"),d=n.parentNode;l.classList.add("mobMenuOpen"),l.classList.add("on-scroll"),document.addEventListener("keydown",c);function c(r){r.keyCode===27&&(o.close(),d.classList.contains("basicLightbox__placeholder")&&(l.classList.remove("mobMenuOpen"),document.removeEventListener("keydown",c),l.classList.toggle("on-scroll")))}l.addEventListener("click",r=>{r.target===n&&(o.close(),d.classList.contains("basicLightbox__placeholder")&&(l.classList.remove("mobMenuOpen"),l.classList.toggle("on-scroll"),document.removeEventListener("keydown",c)))}),o.element().querySelector(".modal-btn").onclick=()=>{o.close(),d.classList.contains("basicLightbox__placeholder")&&(l.classList.remove("mobMenuOpen"),l.classList.toggle("on-scroll"),document.removeEventListener("keydown",c))},i.value="",a.value=""}).catch(s=>{y.error({message:"Unable to send your data. Please correct them and try again.",position:"topRight"});const o=document.createElement("div");o.textContent="Error: Reviews not found",o.style.color="red",o.style.border="1px solid #ed3b44",o.style.borderRadius="15px",o.style.padding="32px"})}const K=document.querySelector(".email-js"),W=document.querySelector(".phone-js");K.addEventListener("click",()=>{window.location.href="mailto:lloydjefferson@gmail.com"});W.addEventListener("click",()=>{window.location.href="tel:+380111111111",console.log(window.location.href)});
//# sourceMappingURL=index.js.map
