import{A as M,S as w,K as h,N as y,a as p,i as S,b as x}from"./assets/vendor-da0xUwRH.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(o){if(o.ep)return;o.ep=!0;const s=n(o);fetch(o.href,s)}})();const L=document.querySelector(".logo-text-js"),E=L.textContent.trim();L.innerHTML="";function q(t){return[...t].map(e=>`<span class="letter-js">${e}</span>`).join("")}L.insertAdjacentHTML("afterbegin",q(E));const T=["About me","Benefits","Projects","FAQ"],C=document.querySelector(".nav-menu-list-js");function P(t){return t.map(e=>` <li class="nav-menu-item-js">
        <a class="nav-menu-link-js" 
          href="#${e.toLowerCase().replace(/\s+/g,"")}" 
          aria-label="go to ${e.toLowerCase()} section">
            ${e}
        </a>
    </li>`).join("")}C.insertAdjacentHTML("afterbegin",P(T));const A=document.querySelector(".header-nav-btn");A.addEventListener("click",$);function $(t){let e;t.target.tagName==="SPAN"?(e=document.querySelector(".nav-menu-list-js"),setTimeout(()=>{e.classList.toggle("menu-visible")},5e3)):(e=document.querySelector(".mobile-menu"),e.addEventListener("click",k)),e.classList.toggle("menu-visible")}function k(t){t.target.classList.contains("menu-visible")||(t.currentTarget.classList.toggle("menu-visible"),t.currentTarget.removeEventListener("click",k))}document.addEventListener("DOMContentLoaded",()=>{new M(".about-me-accordion-list",{duration:400,showMultiple:!0,elementClass:"js-acc-item",triggerClass:"js-toggle-btn",panelClass:"js-accordion-content-wrap",activeClass:"js-ac-content-open"}).open(0)});const R=["HTML/CSS","JavaScript","React","Node.js","React Native","Soft Skills","MySQL"],B=document.querySelector(".js-swiper-list");function O(t){return t.map((e,n)=>`<li class="swiper-slide">
            <p class="js-slide-text">
              ${e}
            </p>
     </li>`).join("")}B.insertAdjacentHTML("afterbegin",O(R));new w(".js-about-me-swiper-wrapper",{modules:[h,y],containerModifierClass:"js-",slideActiveClass:"js-slide-active",loop:!0,loopedSlides:12,slidesPerView:2,simulateTouch:!0,touchRatio:1,watchSlidesProgress:!0,navigation:{nextEl:".js-next-slide-btn"},keyboard:{enabled:!0,onlyInViewport:!0},breakpoints:{768:{slidesPerView:3},1440:{slidesPerView:6}}});const I=["#react","#js","#node js","#git"],N="Programming Across Borders: Ideas, Technologies, Innovations",H="https://alonko68.github.io/project-Portfolio/",V="See project",_=document.querySelectorAll(".projects-slide-content-js");function F(t,e,n,r){return`
    <ul class="slide-content-list-js">${t.map(s=>`<li class="slide-content-item-js">
          <p>${s}</p>
       </li>`).join("")}</ul>
    <p class="slide-content-text-js">${e}</p>
    <a class="slide-content-link-js" href="${n}" target="_blank" rel="noopener noreferrer">
      ${r}
    </a>`}_.forEach(t=>{t.insertAdjacentHTML("afterbegin",F(I,N,H,V))});const f=document.querySelector(".swiper-btn-right-js"),b=document.querySelector(".swiper-btn-left-js");new w(".projects-swiper-js",{direction:"horizontal",simulateTouch:!0,speed:1200,slidesPerView:1,spaceBetween:20,modules:[h,y],navigation:{nextEl:f,prevEl:b},keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!1},on:{reachEnd:()=>{f.disabled=!0},reachBeginning:()=>{b.disabled=!0},fromEdge:()=>{f.disabled=!1,b.disabled=!1}}});new M(".faq-accordion-list",{duration:400,showMultiple:!0});const U=document.querySelector(".covers-section"),W=new IntersectionObserver((t,e)=>{t.forEach(n=>{n.isIntersecting?n.target.classList.add("onScreen"):n.target.classList.remove("onScreen")})},{root:null,rootMargin:"100px",threshold:0});W.observe(U);p.defaults.baseURL="https://portfolio-js.b.goit.study/api";const v=document.querySelector(".reviews-list"),d=document.querySelector(".reviews-next-btn"),u=document.querySelector(".reviews-prev-btn"),m=new w(".reviews-slider",{modules:[y,h],speed:1e3,navigation:{nextEl:".reviews-next-btn",prevEl:".reviews-prev-btn"},breakpoints:{320:{slidesPerGroup:1,slidesPerView:1},768:{slidesPerGroup:2,slidesPerView:2,spaceBetween:16},1440:{slidesPerGroup:4,slidesPerView:4,spaceBetween:16}},keyboard:{enabled:!0,onlyInViewport:!0}});function j(t,e,n){t.isBeginning?e.disabled=!0:e.disabled=!1,t.isEnd?n.disabled=!0:n.disabled=!1}u.addEventListener("click",()=>{j(m,u,d)});d.addEventListener("click",()=>{j(m,u,d)});j(m,u,d);z();async function z(){await p.get("/reviews").then(t=>{v.insertAdjacentHTML("beforeend",D(t.data)),m.update(),document.querySelectorAll(".reviews-text").forEach(e=>{G(e,30)})}).catch(t=>{S.error({message:"We're sorry, but something went wrong: Reviews not found",position:"topRight"});const e=document.createElement("div");e.textContent="Error: Reviews not found",e.style.color="red",e.style.border="1px solid #ed3b44",e.style.borderRadius="15px",e.style.padding="32px",v.innerHTML="",v.appendChild(e)})}function D(t){return t.map(({author:e,avatar_url:n,review:r})=>`<li class="reviews-card swiper-slide">
          <img class="reviews-img" src="${n}" 
            alt="${e}" width="48" height="48" loading="lazy">
          <h3 class="reviews-name">${e}</h3>
          <p class="typewriter reviews-text">${r}</p>
        </li>`).join("")}function G(t,e){t.style.opacity=0,new IntersectionObserver(r=>{r.forEach(o=>{if(o.isIntersecting){let l=function(){i<s.length&&(t.innerHTML+=s.charAt(i),i++,setTimeout(l,e))};if(t.dataset.typingStarted)return;t.dataset.typingStarted="true";const s=t.innerHTML;let i=0;t.innerHTML="",o.target.style.transition=`opacity ${e/1e3}s ease`,o.target.style.opacity=1,l()}})},{threshold:.5}).observe(t)}const a=document.body,K=document.querySelector(".work-together-form");p.defaults.baseURL="https://portfolio-js.b.goit.study/api";async function Q(t,e){return await p.post("/requests/",{email:t,comment:e})}K.addEventListener("submit",J);function J(t){t.preventDefault();const e=t.target,{userEmail:n,userComments:r}=e.elements;Q(n.value,r.value).then(o=>{const s=x.create(` 
        <div id="modalW" class="backdrop">
            <div class="modal-window">
                <button class="modal-btn" type="button" aria-label="close-button">
                     <svg class="modal-btn-icon" xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="none">
                        <path stroke="#FAFAFA" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 7 7 21M7 7l14 14"/>
                    </svg>
                </button>
            <div class="modal-wrapper">
                <h3 class="modal-title">${o.data.title}</h3>
                <p class="modal-text">${o.data.message}</p>
            </div>
            </div>
        </div>`);s.show();const i=document.getElementById("modalW"),l=i.parentNode;a.classList.add("mobMenuOpen"),a.classList.add("on-scroll"),document.addEventListener("keydown",c);function c(g){g.keyCode===27&&(s.close(),l.classList.contains("basicLightbox__placeholder")&&(a.classList.remove("mobMenuOpen"),document.removeEventListener("keydown",c),a.classList.toggle("on-scroll")))}a.addEventListener("click",g=>{g.target===i&&(s.close(),l.classList.contains("basicLightbox__placeholder")&&(a.classList.remove("mobMenuOpen"),a.classList.toggle("on-scroll"),document.removeEventListener("keydown",c)))}),s.element().querySelector(".modal-btn").onclick=()=>{s.close(),l.classList.contains("basicLightbox__placeholder")&&(a.classList.remove("mobMenuOpen"),a.classList.toggle("on-scroll"),document.removeEventListener("keydown",c))},n.value="",r.value=""}).catch(o=>{S.error({message:"Unable to send your data. Please correct them and try again.",position:"topRight"});const s=document.createElement("div");s.textContent="Error: Reviews not found",s.style.color="red",s.style.border="1px solid #ed3b44",s.style.borderRadius="15px",s.style.padding="32px"})}const X=document.querySelector(".email-js"),Y=document.querySelector(".phone-js");X.addEventListener("click",()=>{window.location.href="mailto:lloydjefferson@gmail.com"});Y.addEventListener("click",()=>{window.location.href="tel:+380111111111",console.log(window.location.href)});
//# sourceMappingURL=index.js.map
